### ISSUE TITLE
Not vibrating in iOS, only works in Android

### ISSUE THREAD

**Issue by dark-chocolate** [clovisnicolas/flutter_vibrate#13]
I am using below code

```
// Check if the device can 
bool canVibrate = await Vibrate.
print("canVibrate = ${canVibrate}");  // returns true

Vibrate.vibrate();
```
Still it doesn't vibrate in real device.

Tested in iPhone and iPad pro running 12.0.1

**Comment by dark-chocolate** [comment]
Can anyone help me?
Is there any permission I need to include in iOS?

**Comment by icarus31** [comment]
@dark-chocolate, did you try the example from [here](https://pub.dartlang.org/packages/vibrate#-example-tab-)?

From my side, when using an iphone 5S, only Vibrate.vibrate() and Vibrate.vibrateWithPauses() methods are working.

With my Android phone, only Vibrate.feedback(FeedbackType.selection) and Vibrate.feedback(FeedbackType.impact) methods are not working.

**Comment by dark-chocolate** [comment]
@icarus31 I forgot to come back to this thread. Actually iPad doesn't support vibration and my iPhone 6s was set on mute state. So, when I unmuted it, it start vibrating. 

> With my Android phone, only Vibrate.feedback(FeedbackType.selection) and Vibrate.feedback(FeedbackType.impact) methods are not working.

Have you granted the vibrate permission in your `AndroidManifest.xml` ?

**Comment by icarus31** [comment]
@dark-chocolate I did add `<uses-permission android:name="android.permission.VIBRATE"/>`, and for some reason only those 2 don't work. Not a big deal, but weird.

Regarding my iphone 5s, maybe it is just not supported for the other methods? This is weird the ones described above are working though.

Thanks for your feedback
