### ISSUE TITLE
Build Failed : SWIFT_VERSION

### ISSUE THREAD

**Issue by Solido** [clovisnicolas/flutter_vibrate#7]
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
    === BUILD TARGET Pods-Runner OF PROJECT Pods WITH CONFIGURATION Debug ===
    fatal error: module map file '/Users/user/Documents/app/build/ios/Debug-iphonesimulator/vibrate/vibrate.modulemap' not found
    1 error generated.

**Comment by clovisnicolas** [comment]
Hello, I think you should re-create your project to include Swift support
see https://github.com/clovisnicolas/flutter_vibrate/issues/7
