### ISSUE TITLE
Wrong method called

### ISSUE THREAD

**Issue by isoos** [clovisnicolas/flutter_vibrate#8]
_From @chayawit on July 18, 2018 16:3_

URL: https://pub.dartlang.org/packages/vibrate

The line that says `Vibrate.vibrate(pauses);` should actually be `Vibrate.vibrateWithPauses(pauses);`

_Copied from original issue: dart-lang/pub-dartlang-dart#1468_

**Comment by clovisnicolas** [comment]
Thanks, changed Readme
