### ISSUE TITLE
Are you using Swift 2?

### ISSUE THREAD

**Issue by long1eu** [clovisnicolas/flutter_vibrate#9]

**Comment by clovisnicolas** [comment]
The project is not using swift 2, if you are getting a swift 2 compatibility issue, make sure your project was created with the "Swift compatibility" option.

**Comment by long1eu** [comment]
did you saw this?
https://github.com/flutter/flutter/issues/17999#issuecomment-393108537

**Comment by clovisnicolas** [comment]
That is unfortunate indeed. 
I haven't planned to migrate the plugin to objective C though
